using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;
using BepInEx;
using BepInEx.Configuration;
using BepInEx.Logging;
using HarmonyLib;
using Jotunn.Entities;
using Jotunn.Managers;
using UnityEngine;

namespace ProceduralRoads
{
    [BepInPlugin(ModGUID, ModName, ModVersion)]
    [BepInDependency(Jotunn.Main.ModGuid)]
    public class ProceduralRoadsPlugin : BaseUnityPlugin
    {
        internal const string ModName = "ProceduralRoads";
        internal const string ModVersion = "1.9.0";
        internal const string Author = "warpalicious";
        private const string ModGUID = Author + "." + ModName;
        private static string ConfigFileName = ModGUID + ".cfg";
        private static string ConfigFileFullPath = Paths.ConfigPath + Path.DirectorySeparatorChar + ConfigFileName;
        internal static string ConnectionError = "";
        private readonly Harmony _harmony = new(ModGUID);

        public static readonly ManualLogSource ProceduralRoadsLogger = BepInEx.Logging.Logger.CreateLogSource(ModName);

        // Location Manager variables
        public Texture2D tex = null!;

        // Use only if you need them
        //private Sprite mySprite = null!;
        //private SpriteRenderer sr = null!;

        public enum Toggle
        {
            On = 1,
            Off = 0
        }

        // Configuration entries
        public static ConfigEntry<float> RoadWidth = null!;
        public static ConfigEntry<RockClearingMode> RockClearing = null!;
        public static ConfigEntry<string> CustomLocations = null!;
        public static ConfigEntry<int> CustomLocationPriority = null!;
        public static ConfigEntry<Heightmap.Biome> ExcludedRoadBiomes = null!;
        public static ConfigEntry<bool> RoutedConnections = null!;
        public static ConfigEntry<bool> WalkableIslands = null!;
        public static ConfigEntry<bool> CoastalLandings = null!;
        public static ConfigEntry<bool> SelectIslandsByContent = null!;
        public static ConfigEntry<bool> WeightedDestinations = null!;
        public static ConfigEntry<int> TargetSubAreas = null!;
        public static ConfigEntry<int> IslandRoadPercentage = null!;
        public static ConfigEntry<int> PathfindingMaxIterations = null!;
        public static ConfigEntry<int> MaxLocationsPerIsland = null!;
        public static ConfigEntry<float> FordWadeWeight = null!;
        public static ConfigEntry<float> FordRaiseWeight = null!;
        public static ConfigEntry<float> FordSpanWeight = null!;
        public static ConfigEntry<float> BridgeCostFixed = null!;
        public static ConfigEntry<float> BridgeCostPerMeter = null!;
        public static ConfigEntry<float> MaxGrade = null!;

        public void Awake()
        {
            // Register the metadata prefab with Jotunn FIRST - must happen before ZNetScene.Awake
            RegisterMetadataPrefab();
            
            bool saveOnSet = Config.SaveOnConfigSet;
            Config.SaveOnConfigSet = false;

            // Initialize configuration
            RoadWidth = Config.Bind("Roads", "RoadWidth", 4f,
                new ConfigDescription("Width of generated roads in meters",
                    new AcceptableValueRange<float>(2f, 10f)));

            IslandRoadPercentage = Config.Bind("Roads", "IslandRoadPercentage", 33,
                new ConfigDescription("Percentage of islands selected for roads. A boss does not automatically select its island. " +
                    "Zero disables generation. Existing saved networks are not regenerated by changing settings.",
                    new AcceptableValueRange<int>(0, 100)));

            PathfindingMaxIterations = Config.Bind("Roads", "PathfindingMaxIterations", RoadConstants.PathfindingMaxIterations,
                new ConfigDescription("Maximum number of iterations for each road segment's pathfinding algorithm. " +
                    "Higher values will generate more roads but increase generation time. " +
                    "Lower values will speed up generation time but cause less roads to generate.",
                    new AcceptableValueRange<int>(1000, 100000)));

            MaxLocationsPerIsland = Config.Bind("Roads", "MaxLocationsPerIsland", 48,
                new ConfigDescription("Destination budget per island. Required boss/quest sites and selected coastal landings count toward it " +
                    "but are retained even when they exceed it.",
                    new AcceptableValueRange<int>(2, 128)));

            FordWadeWeight = Config.Bind("Fords", "WadeWeight", RoadConstants.DefaultFordStyleWeight,
                new ConfigDescription("Relative odds that a ford is WADED, the road painted through the shallows at ground height " +
                    "(offered only where the water is ankle deep, always in swamps). 0 disables the style; with equal weights each site picks evenly among the styles it allows.",
                    new AcceptableValueRange<float>(0f, 100f)));

            FordRaiseWeight = Config.Bind("Fords", "RaiseWeight", RoadConstants.DefaultFordStyleWeight,
                new ConfigDescription("Relative odds that a ford is RAISED, the road leveled up through the shallows. " +
                    "Always allowed, and used whenever no other style is.",
                    new AcceptableValueRange<float>(0f, 100f)));

            FordSpanWeight = Config.Bind("Fords", "SpanWeight", RoadConstants.DefaultFordStyleWeight,
                new ConfigDescription("Relative odds that a ford is SPANNED by a short low footbridge with a step at each end " +
                    "(offered only where the crossing is at least 6 m wide).",
                    new AcceptableValueRange<float>(0f, 100f)));

            BridgeCostFixed = Config.Bind("Bridges", "CostFixed", RoadConstants.DefaultBridgeCostFixed,
                new ConfigDescription("Pathfinding cost of a bridge, fixed part. " +
                    "For scale: easy ground costs about 1 per metre of road, rough or steep ground 1000-2000 per 8 m cell. " +
                    "Lower = more bridges, higher = roads go around instead.",
                    new AcceptableValueRange<float>(0f, 1000000f)));

            BridgeCostPerMeter = Config.Bind("Bridges", "CostPerMeter", RoadConstants.DefaultBridgeCostPerMeter,
                new ConfigDescription("Pathfinding cost of a bridge per metre of span, on top of CostFixed. " +
                    "Makes long bridges dearer than short ones.",
                    new AcceptableValueRange<float>(0f, 10000f)));
            MaxGrade = Config.Bind("Roads", "MaxGrade", RoadConstants.DefaultMaxRoadGrade,
                new ConfigDescription("Steepest a road may climb, as rise over run: 0.35 is one metre up " +
                    "for every three along, about 19 degrees. The road you walk never exceeds it: the " +
                    "height it is built at is held to this value. Route finding is allowed 0.10 more " +
                    "than this over the raw ground, because the ground a road crosses is not the " +
                    "profile it is finally built to; a route found that way is still refused if its " +
                    "built profile cannot stay inside the cap. A destination reachable only by a " +
                    "steeper climb is left without a road rather than given one too steep to walk. " +
                    "Lower values mean gentler roads, longer detours and more destinations left out. " +
                    "0 removes the cap entirely, for route finding as well.",
                    new AcceptableValueRange<float>(0f, 1f)));

            CustomLocations = Config.Bind("Locations", "CustomLocations", "",
                "Comma-separated list of location names to include in road generation. " +
                "Use this for locations added by Expand World Data or other mods. " +
                "Example: Runestone_Boars,Runestone_Greydwarfs,MerchantCamp");

            // Locations level the ground under themselves when they are
            // placed; roads are built before that happens, so the generator
            // needs a way to ask what that ground will be.
            LocationPrefabLevelling.Install();
            CustomLocationPriority = Config.Bind("Locations", "CustomLocationPriority", 80,
                new ConfigDescription("Selection weight for custom locations discovered by prefix, config or API.",
                    new AcceptableValueRange<int>(1, 100)));
            ExcludedRoadBiomes = Config.Bind("Locations", "ExcludedRoadBiomes",
                Heightmap.Biome.AshLands | Heightmap.Biome.DeepNorth,
                "Biomes excluded from every destination source, including API registrations and required sites. " +
                "This filters destinations; it does not forbid a route passing through a biome.");
            RoutedConnections = Config.Bind("Roads", "RoutedConnections", true,
                "Plan connections using sampled route costs, then join destinations to existing roads where possible. " +
                "False keeps the previous chain/MST choice.");
            WalkableIslands = Config.Bind("Roads", "WalkableIslands", true,
                "Group walkable land and nearby crossable water instead of using coarse base-height islands. " +
                "This is a grouping approximation, not a guarantee that a road can cross.");
            CoastalLandings = Config.Bind("Roads", "CoastalLandings", true,
                "Include possible coastal boat approaches on selected islands, roughly one per 5 square kilometres. " +
                "Uses WalkableIslands samples; disabled with the coarse legacy detector. No docks are spawned, " +
                "and terrain may prevent a road or boat from reaching a selected landing.");
            SelectIslandsByContent = Config.Bind("Roads", "SelectIslandsByContent", true,
                "Prefer islands with more eligible destinations; false prefers larger islands.");
            WeightedDestinations = Config.Bind("Roads", "WeightedDestinations", true,
                "Choose a seeded mix of destinations by importance and distance. False uses priority ranking.");
            RockClearing = Config.Bind("Roads", "RockClearing", RockClearingMode.Carve,
                "Natural rocks that clip a road's surface. Off leaves them; Remove takes away a rock that blocks " +
                "at least half the road's width; Carve takes only the pieces of a rock that stand in the road, as a " +
                "pickaxe would, and drops no stone. Helps mountain and Mistlands roads most, where boulders otherwise " +
                "make them hard to use. Location parts and player pieces are never touched.");
            RoadRockClearing.Mode = RockClearing.Value;
            RockClearing.SettingChanged += (_, _) => RoadRockClearing.Mode = RockClearing.Value;
            TargetSubAreas = Config.Bind("Roads", "TargetSubAreas", 9,
                new ConfigDescription("Approximate number of sub-areas used to spread destinations over an island. " +
                    "Zero disables spreading. The actual number depends on island shape.",
                    new AcceptableValueRange<int>(0, 25)));

            // Apply config to road generator
            ApplyConfiguration();

            Assembly assembly = Assembly.GetExecutingAssembly();
            ManualRoadNetworkSync.Register();
            _harmony.PatchAll(assembly);
            SetupWatcher();

            Analytics.Init(Config, ModGUID, ModVersion);


            if (saveOnSet)
            {
                Config.SaveOnConfigSet = saveOnSet;
                Config.Save();
            }
        }

        /// <summary>
        /// Register the metadata prefab with Jotunn's PrefabManager.
        /// This creates an empty, invisible GameObject that will be used to store road data.
        /// Must be called before ZNetScene.Awake so the prefab is registered in time.
        /// </summary>
        private void RegisterMetadataPrefab()
        {
            // Create an empty GameObject - no mesh, no collider, completely invisible
            var prefab = new GameObject(RoadNetworkGenerator.MetadataPrefabName);

            // Added to an active object, the ZNetView would run Awake at once, find
            // no ZDOMan yet and destroy itself. The prefab would then have no
            // ZNetView: every copy the game made for the saved metadata ZDO left
            // the ZDO unclaimed ("ZDO ... not used when creating object"), so it
            // was made again the next frame, leaking an object each time.
            // Inactive while the component is added, then parented under Jotunn's
            // inactive prefab container, the prefab never wakes; copies do.
            prefab.SetActive(false);
            var nview = prefab.AddComponent<ZNetView>();
            nview.m_persistent = true;

            // Wrap in CustomPrefab and register with Jotunn
            var customPrefab = new CustomPrefab(prefab, false);
            PrefabManager.Instance.AddPrefab(customPrefab);
            prefab.SetActive(true);

            ProceduralRoadsLogger.LogDebug($"Registered metadata prefab: {RoadNetworkGenerator.MetadataPrefabName}");
        }

        private static void ApplyConfiguration()
        {
            RoadNetworkGenerator.RoadWidth = RoadWidth.Value;
            RoadNetworkGenerator.IslandRoadPercentage = IslandRoadPercentage.Value;
            // A validation switch, not a setting: see DebugSwitches.
            RoadNetworkGenerator.GenerateOnLoad = DebugSwitches.Flag("GENERATE_ROADS_ON_LOAD", true);
            // How many islands may be built at once. Unset is what the mod
            // does on its own -- one fewer than the machine reports -- and 1
            // is the fully serial path. A validation switch for measuring
            // worker counts against each other, not a setting: the right
            // number is a property of the machine, not of the player's taste.
            RoadParallel.Configured = DebugSwitches.Count("ISLAND_WORKERS", 0, 0, 256);
            RoadNetworkGenerator.MaxLocationsPerIsland = MaxLocationsPerIsland.Value;
            RoadNetworkGenerator.NetworkOptions = new RoadNetworkOptions
            {
                CustomLocationPriority = CustomLocationPriority.Value,
                ExcludedBiomes = ExcludedRoadBiomes.Value,
                RoutedConnections = RoutedConnections.Value,
                WalkableIslands = WalkableIslands.Value,
                CoastalLandings = CoastalLandings.Value,
                ContentFirst = SelectIslandsByContent.Value,
                WeightedDestinations = WeightedDestinations.Value,
                TargetSubAreas = TargetSubAreas.Value
            };
            RoadPathfinder.MaxIterations = PathfindingMaxIterations.Value;
            RoadCrossingDetector.SetFordStyleWeights(FordWadeWeight.Value, FordRaiseWeight.Value, FordSpanWeight.Value);
            RoadPathfinder.ConfiguredBridgeCostFixed = BridgeCostFixed.Value;
            RoadPathfinder.ConfiguredBridgeCostPerMeter = BridgeCostPerMeter.Value;
            RoadGrade.Configured = MaxGrade.Value;
            // CustomLocations is parsed at generation time to preserve API registrations
        }

        /// <summary>
        /// Parse the CustomLocations config string into a list of location names.
        /// Called at generation time to merge with API-registered locations.
        /// </summary>
        public static HashSet<string> GetConfigLocationNames()
        {
            var result = new HashSet<string>();
            
            if (string.IsNullOrWhiteSpace(CustomLocations.Value))
                return result;

            string[] locationNames = CustomLocations.Value.Split(',');
            foreach (string name in locationNames)
            {
                string trimmed = name.Trim();
                if (!string.IsNullOrEmpty(trimmed))
                {
                    result.Add(trimmed);
                }
            }
            
            return result;
        }

        private float m_nextTerrainSweep;

        // Road terrain the zone-spawn path missed (see RoadTerrainModifier.SweepUnstamped).
        private void Update()
        {
            if (Time.time < m_nextTerrainSweep) return;
            m_nextTerrainSweep = Time.time + 3f;
            if (RoadNetworkGenerator.RoadsAvailable && ZNet.instance != null)
                RoadTerrainModifier.SweepUnstamped();
        }

        // Rocks clipping the roads, on their own half-second cadence (RoadRockClearing).
        private void LateUpdate()
        {
            RoadRockClearing.Tick();
        }

        private void OnDestroy()
        {
            Config.Save();
        }

        private void SetupWatcher()
        {
            FileSystemWatcher watcher = new(Paths.ConfigPath, ConfigFileName);
            watcher.Changed += ReadConfigValues;
            watcher.Created += ReadConfigValues;
            watcher.Renamed += ReadConfigValues;
            watcher.IncludeSubdirectories = true;
            watcher.SynchronizingObject = ThreadingHelper.SynchronizingObject;
            watcher.EnableRaisingEvents = true;
        }

        private void ReadConfigValues(object sender, FileSystemEventArgs e)
        {
            if (!File.Exists(ConfigFileFullPath)) return;
            try
            {
                ProceduralRoadsLogger.LogDebug("ReadConfigValues called");
                Config.Reload();
                ApplyConfiguration();
            }
            catch
            {
                ProceduralRoadsLogger.LogError($"There was an issue loading your {ConfigFileName}");
                ProceduralRoadsLogger.LogError("Please check your config entries for spelling and format!");
            }
        }


    }

    public static class KeyboardExtensions
    {
        public static bool IsKeyDown(this KeyboardShortcut shortcut)
        {
            return shortcut.MainKey != KeyCode.None && Input.GetKeyDown(shortcut.MainKey) &&
                   shortcut.Modifiers.All(Input.GetKey);
        }

        public static bool IsKeyHeld(this KeyboardShortcut shortcut)
        {
            return shortcut.MainKey != KeyCode.None && Input.GetKey(shortcut.MainKey) &&
                   shortcut.Modifiers.All(Input.GetKey);
        }
    }
}
